system:
  name: "ANR/Tombstone AI Analyzer"
  version: "1.0.0"

api:
  host: "0.0.0.0"
  port: 5000
  workers: 4
  timeout: 300

providers:
  anthropic:
    enabled: true
    default_model: "claude-sonnet-4-20250514"
  openai:
    enabled: true
    default_model: "gpt-4o"

analysis_modes:
  quick:
    chunk_size: 50000
    max_tokens: 2000
    timeout: 120
  intelligent:
    chunk_size: 150000
    max_tokens: 8000
    timeout: 300
  large_file:
    chunk_size: 200000
    max_tokens: 8000
    timeout: 600
  max_token:
    chunk_size: 180000
    max_tokens: 16000
    timeout: 900

limits:
  max_file_size_mb: 20
  max_concurrent_analyses: 5
  default_budget_usd: 10.0

cache:
  enabled: true
  ttl_hours: 24

logging:
  level: "INFO"
  format: "json"
  directory: "logs"
